Adding sample async hooks files
DoctrineLegal/doctrine-open-source pull request #2
Opened 2019-03-27 07:58 UTC by xblondel-doctrine

Adding sample async hooks files, for long asynchronous operations analysis.

2019-03-28 10:20 UTC, eclivus requested changes

2019-03-28 10:20 UTC, eclivus commented on analyzeLongSyncOpsInProfilingData/asyncHooksDoctrine.js
> +if (! process.env.DISABLE_ASYNC_HOOKS) {
mérite sa place dans le README

2019-03-28 10:20 UTC, eclivus commented on analyzeLongSyncOpsInProfilingData/computationCost.js
> +  heapdump.writeSnapshot('doctrine.heapsnapshot')
occurence de doctrine

2019-03-28 10:20 UTC, eclivus commented on analyzeLongSyncOpsInProfilingData/computationCost.js
> +During the accident on April 17th, 2018, we reached:
trop spécifique à nous

2019-03-28 10:20 UTC, eclivus commented on analyzeLongSyncOpsInProfilingData/computationCost.js
> +const LOG_MEMORY_EVERY = (process.env.NODE_ENV === 'production') ? 10000 : 120000
trop spécifique

2019-03-28 10:20 UTC, eclivus commented on analyzeLongSyncOpsInProfilingData/computationCost.js
> +const LOG_SYNC_TIMES_EVERY = (process.env.NODE_ENV === 'production' || process.env.DEBUG_LOG_SYNC_TIMES) ? 10000 : 120000
same

2019-03-28 10:20 UTC, eclivus commented on analyzeLongSyncOpsInProfilingData/computationCost.js
> +  async.series([
je vois pas trop en quoi computation_cost a un rapport avec asyncHooks

2019-03-28 10:20 UTC, eclivus commented on analyzeLongSyncOpsInProfilingData/computationCost.js
> +function printMemoryUsage(memory_usage) {
ce genre de helpers est hors contexte aussi

2019-03-28 10:20 UTC, eclivus commented on analyzeLongSyncOpsInProfilingData/computationCost.js
> +function logMemoryUsage() {
same + propre à AWS

2019-03-28 10:20 UTC, eclivus commented on analyzeLongSyncOpsInProfilingData/computationCost.js
> + * Prints a line of this format with 10 integers:
razpport avec async hooks ?

2019-03-28 10:20 UTC, eclivus commented on analyzeLongSyncOpsInProfilingData/computationCost.js
> + * Prints a line of this format with 10 integers:
et trop spécifique

2019-04-23 12:28 UTC, xblondel-doctrine commented
Because of the amount of work required to make a generic version of these files, and since the blog post has been published in the meantime, without reference to these files, I close this PR.

2019-04-23 12:28 UTC, closed without merging